# Generated by Django 5.0 on 2023-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='img/featured_image.jpg', upload_to='img/featured_images'),
        ),
    ]
